CREATE TABLE [adi].[WellcareAltusProviderMbr] (
    [mbrWlcMbrByPcpKey]     INT           IDENTITY (1, 1) NOT NULL,
    [IPA_NAME]              VARCHAR (50)  NULL,
    [PCP_NAME]              VARCHAR (50)  NULL,
    [SUBSCRIBER_ID]         VARCHAR (50)  NULL,
    [DOB]                   DATE          NULL,
    [LANGUAGE]              VARCHAR (50)  NULL,
    [MEMBER_NAME]           VARCHAR (50)  NULL,
    [ADDRESS_1]             VARCHAR (100) NULL,
    [ADDRESS_2]             VARCHAR (50)  NULL,
    [CITY]                  VARCHAR (50)  NULL,
    [STATE]                 VARCHAR (20)  NULL,
    [ZIP_CODE]              VARCHAR (20)  NULL,
    [HOME_PHONE_NUMBER]     VARCHAR (20)  NULL,
    [MOBILE_PHONE]          VARCHAR (20)  NULL,
    [MEMBER_EFFECTIVE_DATE] DATE          NULL,
    [SrcFileName]           VARCHAR (100) NOT NULL,
    [LoadDate]              DATE          NOT NULL,
    [DataDate]              DATE          NOT NULL,
    [CreateDate]            DATETIME2 (7) CONSTRAINT [Df_WellcareAltusProviderMbr_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreateBy]              VARCHAR (50)  CONSTRAINT [Df_WellcareAltusProviderMbr_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [LastUpdatedDate]       DATETIME2 (7) CONSTRAINT [DF_WellcareAltusProviderMbr_LastUpdatedDate] DEFAULT (getdate()) NOT NULL,
    [LastUpdatedBy]         VARCHAR (50)  CONSTRAINT [DF_WellcareAltusProviderMbr_LastUpdatedBy] DEFAULT (suser_sname()) NOT NULL,
    [MbrLoadStatus]         INT           CONSTRAINT [DF_WellcareAltusProviderMbrLoadStatus] DEFAULT ((0)) NULL,
    [MEMBER_LAST_NAME]      VARCHAR (50)  NULL,
    [MEMBER_FIRST_NAME]     VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([mbrWlcMbrByPcpKey] ASC)
);

