



CREATE VIEW [dbo].[vw_ActiveMembers]
AS
/* version history: 
    12/02/2019: GK Added a MbrMember.ClientKey <> 1 clause for rollout of mbr Model 
	2021-02-03: Brit 
    */
SELECT distinct --t.mbrMemberKey,
       t.CLIENT, t.clientKey,
       t.MEMBER_ID,
       t.MEMBER_FIRST_NAME,
       t.MEMBER_MI,
       t.MEMBER_LAST_NAME,
       t.CLIENT_SUBSCRIBER_ID,
	  t.Ace_ID,
       t.PLAN_ID,
       t.PRODUCT_CODE,
       t.SUBGRP_ID,
       t.SUBGRP_NAME,
       t.MEDICAID_ID,
       t.AGE,
       t.DATE_OF_BIRTH,
       t.GENDER,
       t.LANG_CODE,
       t.ETHNICITY,
       t.RACE,
       t.MEMBER_HOME_ADDRESS,
       t.MEMBER_HOME_ADDRESS2,
       t.MEMBER_HOME_CITY,
       t.MEMBER_HOME_STATE,
       t.MEMBER_HOME_ZIP_C,
       t.MEMBER_HOME_PHONE,
       t.MEMBER_MAIL_ADDRESS,
       t.MEMBER_MAIL_ADDRESS2,
       t.MEMBER_MAIL_CITY,
       t.MEMBER_MAIL_STATE,
       t.MEMBER_MAIL_ZIP_C,
       t.MEMBER_MAIL_PHONE,
       t.MEMBER_COUNTY,
       t.MEMBER_BUS_PHONE,
       t.MEMBER_ORG_EFF_DATE,
       t.MEMBER_CONT_EFF_DATE,
       t.MEMBER_CUR_EFF_DATE,
       t.MEMBER_CUR_TERM_DATE,
       t.PCP_CLIENT_ID,
       t.PCP_FIRST_NAME,
       t.PCP_LAST_NAME,
       t.NPI,
	  t.PCP_AccountType,
       t.PCP_PHONE,
       t.PCP_FAX,
       t.PCP_ADDRESS,
       t.PCP_ADDRESS2,
       t.PCP_CITY,
       t.PCP_STATE,
       t.PCP_ZIP_C,
       t.PCP_EFFECTIVE_DATE,
       t.PCP_TERM_DATE,
       t.PCP_PRACTICE_TIN,
       t.PCP_GROUP_ID,
       RTRIM(LTRIM(t.PCP_PRACTICE_NAME)) AS PCP_PRACTICE_NAME,
       t.AUTO_ASSIGN,
       t.MEMBER_STATUS,
       t.MEMBER_TERM_DATE,
       t.ClientRiskScore AS IPRO_ADMIT_RISK_SCORE,
       t.RISK_CATEGORY_C,
       t.LINE_OF_BUSINESS,
       t.PLAN_CODE,
       t.PLAN_DESC,
       t.PRIMARY_RISK_FACTOR,
       t.TOTAL_COSTS_LAST_12_MOS,
       t.COUNT_OPEN_CARE_OPPS,
       t.INP_COSTS_LAST_12_MOS,
       t.ER_COSTS_LAST_12_MOS,
       t.OUTP_COSTS_LAST_12_MOS,
       t.PHARMACY_COSTS_LAST_12_MOS,
       t.PRIMARY_CARE_COSTS_LAST_12_MOS,
       t.BEHAVIORAL_COSTS_LAST_12_MOS,
       t.OTHER_OFFICE_COSTS_LAST_12_MOS,
       t.INP_ADMITS_LAST_12_MOS,
       t.LAST_INP_DISCHARGE,
       t.POST_DISCHARGE_FUP_VISIT,
       t.INP_FUP_WITHIN_7_DAYS,
       t.ER_VISITS_LAST_12_MOS,
       t.LAST_ER_VISIT,
       t.POST_ER_FUP_VISIT,
       t.ER_FUP_WITHIN_7_DAYS,
       t.LAST_PCP_VISIT,
       t.LAST_PCP_PRACTICE_SEEN,
       t.LAST_BH_VISIT,
       t.LAST_BH_PRACTICE_SEEN,
       t.MEMBER_MONTH_COUNT,
       t.MEMBER_POD_C,
       t.MEMBER_POD_DESC,
       t.PCP_POD_C,
       t.PCP_POD_DESC,
       t.PCP_NAME,
       t.CLIENT_UNIQUE_SYSTEM_ID,
       t.MEDICARE_ID,
       t.RESP_LAST_NAME,
       t.RESP_FIRST_NAME,
       t.RESP_ADDRESS,
       t.RESP_ADDRESS2,
       t.RESP_CITY,
       t.RESP_STATE,
       t.RESP_ZIP,
       t.RESP_PHONE,
	  t.AhsPlanCode,
	  t.AhsPlanName,
	  t.CurMonthsOld, 
	  t.CurYearsOld,
	  t.LoadDate	  
FROM [dbo].[tvf_Activemembers](GETDATE()) t
    WHERE t.ClientKey <> 1

/* Old Uhc Data store */
union all
SELECT 'UHC' as CLIENT, 1 AS ClientKey,
	   a.MEMBER_ID,
       a.MEMBER_FIRST_NAME,
       a.MEMBER_MI,
       a.MEMBER_LAST_NAME,
       a.UHC_SUBSCRIBER_ID as CLIENT_SUBSCRIBER_ID,
	  a.Ace_ID,
       a.PLAN_ID,
       a.PRODUCT_CODE,
       a.SUBGRP_ID,
       a.SUBGRP_NAME,
       a.MEDICAID_ID,
       a.AGE,
       a.DATE_OF_BIRTH,
       a.GENDER,
       a.LANG_CODE,
       a.ETHNICITY,
       a.RACE,
       a.MEMBER_HOME_ADDRESS,
       a.MEMBER_HOME_ADDRESS2,
       a.MEMBER_HOME_CITY,
       a.MEMBER_HOME_STATE,
       a.MEMBER_HOME_ZIP_C,
       a.MEMBER_HOME_PHONE,
       a.MEMBER_MAIL_ADDRESS,
       a.MEMBER_MAIL_ADDRESS2,
       a.MEMBER_MAIL_CITY,
       a.MEMBER_MAIL_STATE,
       a.MEMBER_MAIL_ZIP_C,
       a.MEMBER_MAIL_PHONE,
       a.MEMBER_COUNTY,
       a.MEMBER_BUS_PHONE,
       a.MEMBER_ORG_EFF_DATE,
       a.MEMBER_CONT_EFF_DATE,
       a.MEMBER_CUR_EFF_DATE,
       a.MEMBER_CUR_TERM_DATE,
       a.PCP_UHC_ID AS PCP_CLIENT_ID,
       a.PCP_FIRST_NAME,
       a.PCP_LAST_NAME,
       a.PCP_NPI AS NPI,
	  a.PCP_AccountType,
       a.PCP_PHONE,
       a.PCP_FAX,
       a.PCP_ADDRESS,
       a.PCP_ADDRESS2,
       a.PCP_CITY,
       a.PCP_STATE,
       a.PCP_ZIP_C,
       a.PCP_EFFECTIVE_DATE,
       a.PCP_TERM_DATE,
       a.PCP_PRACTICE_TIN,
       a.PCP_GROUP_ID,
       a.PCP_PRACTICE_NAME,
       a.AUTO_ASSIGN,
       a.MEMBER_STATUS,
       a.MEMBER_TERM_DATE,
       a.IPRO_ADMIT_RISK_SCORE,
       a.RISK_CATEGORY_C,
       a.LINE_OF_BUSINESS,
       a.PLAN_CODE,
       a.PLAN_DESC,
       a.PRIMARY_RISK_FACTOR,
       a.TOTAL_COSTS_LAST_12_MOS,
       a.COUNT_OPEN_CARE_OPPS,
       a.INP_COSTS_LAST_12_MOS,
       a.ER_COSTS_LAST_12_MOS,
       a.OUTP_COSTS_LAST_12_MOS,
       a.PHARMACY_COSTS_LAST_12_MOS,
       a.PRIMARY_CARE_COSTS_LAST_12_MOS,
       a.BEHAVIORAL_COSTS_LAST_12_MOS,
       a.OTHER_OFFICE_COSTS_LAST_12_MOS,
       a.INP_ADMITS_LAST_12_MOS,
       a.LAST_INP_DISCHARGE,
       a.POST_DISCHARGE_FUP_VISIT,
       a.INP_FUP_WITHIN_7_DAYS,
        try_convert(NUMERIC(10,2), a.ER_VISITS_LAST_12_MOS) as ER_VISITS_LAST_12_MOS,
       a.LAST_ER_VISIT,
       a.POST_ER_FUP_VISIT,
       a.ER_FUP_WITHIN_7_DAYS,
       a.LAST_PCP_VISIT,
       a.LAST_PCP_PRACTICE_SEEN,
       a.LAST_BH_VISIT,
       a.LAST_BH_PRACTICE_SEEN,
       a.MEMBER_MONTH_COUNT,
       a.MEMBER_POD_C,
       a.MEMBER_POD_DESC,
       a.PCP_POD_C,
       a.PCP_POD_DESC,
       a.PCP_NAME,
       a.UHC_UNIQUE_SYSTEM_ID AS CLIENT_UNIQUE_SYSTEM_ID,
       a.MEDICARE_ID,
       a.RESP_LAST_NAME,
       a.RESP_FIRST_NAME,
       a.RESP_ADDRESS,
       a.RESP_ADDRESS2,
       a.RESP_CITY,
       a.RESP_STATE,
       a.RESP_ZIP,
       a.RESP_PHONE,
	  a.AhsPlanCode,
	  a.AhsPlanName,
	  a.CurMonthsOld, 
	  a.CurYearsOld,
	  a.loadDate
FROM vw_UHC_Activemembers a
;


 



